// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDMrZXeZvs7H-3sclMfwzvxDTgZ2f-2fY',
    appId: '1:907283981512:web:da9f5629e5413506ebf1fd',
    messagingSenderId: '907283981512',
    projectId: 'moviehub-b2ab5',
    authDomain: 'moviehub-b2ab5.firebaseapp.com',
    storageBucket: 'moviehub-b2ab5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSb38rTZNNjk23iAoJh-9xZmaLS3Mvz0',
    appId: '1:907283981512:android:e779f264cfb08828ebf1fd',
    messagingSenderId: '907283981512',
    projectId: 'moviehub-b2ab5',
    storageBucket: 'moviehub-b2ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUPLRUAaYfuJKJQ4fZsqkp3s5mMGBo4k',
    appId: '1:907283981512:ios:a9127cc39f6bb024ebf1fd',
    messagingSenderId: '907283981512',
    projectId: 'moviehub-b2ab5',
    storageBucket: 'moviehub-b2ab5.firebasestorage.app',
    iosBundleId: 'com.example.moviehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUPLRUAaYfuJKJQ4fZsqkp3s5mMGBo4k',
    appId: '1:907283981512:ios:a9127cc39f6bb024ebf1fd',
    messagingSenderId: '907283981512',
    projectId: 'moviehub-b2ab5',
    storageBucket: 'moviehub-b2ab5.firebasestorage.app',
    iosBundleId: 'com.example.moviehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDMrZXeZvs7H-3sclMfwzvxDTgZ2f-2fY',
    appId: '1:907283981512:web:3fe5058d309a967febf1fd',
    messagingSenderId: '907283981512',
    projectId: 'moviehub-b2ab5',
    authDomain: 'moviehub-b2ab5.firebaseapp.com',
    storageBucket: 'moviehub-b2ab5.firebasestorage.app',
  );
}
