import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'screens/splash_screen.dart';
import 'screens/home_screen.dart'; // Assuming this is the path to HomeScreen
import 'screens/login_screen.dart'; // Replace with the actual path to your login screen

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Required for async initialization
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Loads Firebase config
  );
  runApp(const MovieHubApp());
}

class MovieHubApp extends StatelessWidget {
  const MovieHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MovieHub',
      theme: ThemeData(
        primaryColor: const Color(0xFF00203F),
        colorScheme: ColorScheme.fromSwatch().copyWith(
          secondary: const Color(0xFF0D3B66),
        ),
        fontFamily: 'Poppins',
        textTheme: const TextTheme(
          bodyLarge: TextStyle(color: Color(0xFFFFFFFF)),
          bodyMedium: TextStyle(color: Color(0xFFFFFFFF)),
          titleLarge: TextStyle(color: Color(0xFFFFFFFF)),
        ),
      ),
      initialRoute: '/splash', // Start with splash screen
      routes: {
        '/splash': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(), // Replace with your actual login screen
        '/home': (context) => const HomeScreen(),
      },
    );
  }
}